[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"


[project]
name = "kikuchi-vae"
version = "0.1.0"
description = "VAE for Kikuchi pattern representation learning"
readme = "README.md"

requires-python = ">=3.10"

dependencies = [
    "torch",
    "torchvision",
    "huggingface_hub",
    "numpy",
    "pillow",
]


[tool.setuptools.packages.find]
where = ["src"]